insert into `provinces` values ('NL', 'Newfoundland and Labrador', 'Atlantic');
insert into `provinces` values ('PE', 'Prince Edward Island', 'Atlantic');
insert into `provinces` values ('NS', 'Nova Scotia', 'Atlantic');
insert into `provinces` values ('NB', 'New Brunswick', 'Atlantic');
insert into `provinces` values ('QC', 'Quebec', 'Quebec');
insert into `provinces` values ('ON', 'Ontario', 'Ontario');
insert into `provinces` values ('MB', 'Manitoba', 'Prairies');
insert into `provinces` values ('SK', 'Saskatchewan', 'Prairies');
insert into `provinces` values ('AB', 'Alberta', 'Prairies');
insert into `provinces` values ('BC', 'British Columbia', 'British Columbia');
insert into `provinces` values ('YT', 'Yukon', 'Territories');
insert into `provinces` values ('NT', 'Northwest Territories', 'Territories');
insert into `provinces` values ('NU', 'Nunavut', 'Territories');
